version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-container
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=${APP_ENV:-development}
    networks:
      - app-network
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8040:80"
    networks:
      - app-network
    depends_on:
      - php

  redis:
    image: redis:latest
    container_name: redis-container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
